---
title: 'D-place FARM documentation: Master script'
author: "Ty Tuff, Bruno Vilela, and Carlos Botero"
date: 'project began: 15 May 2016, document updated: `r strftime(Sys.time(), format
  = "%d %B %Y")`'
output:
  html_notebook: default
  html_document: default
  pdf_document: default
  word_document: default
bibliography: FARM package.bib
---

# Calling modules: the master script for all modules


```{r}
# Install the most recent version of FARM from a .zip file
install.packages(file.choose(), repos=NULL) 
```

```{r}
library(FARM)
ls("package:FARM")
```


```{r}
#This is not used right now. It can be useful if we want to predetermine the probabilities of thinks but currently we are drawing random numbers as we go. 
parameters.table
```




```{r}
#####################################################################
## need to document which functions we use from each of these libraries. 
library(ape)
library(spdep)
library(Rcpp)
library(msm)
library(FARM)
```





```{r}


#####################################################################

# Run the full model in a cluster. This version writes files to a cluster output folder.
# rm(list = ls())
# install.packages("~/Desktop/FARM_1.0.tar.gz", repos=NULL, type="source")





sim_run_cluster <- function(replicate_cycle, myWorld, number_of_time_steps, nbs,
                            number_of_tips) {
  # Calls the full simulation script 
  #	 
  # Purpose: Need to wrap the entire simulation script into a function so it can be called in parallel from a cluster call 	
  #
  # Args:
  #    replicate_cycle: An integer indicating the replicate number of a simulation. This variable is used in this function to label        
  #			the saved output file and control the number of replicates run by the cluster.
  #
  #    combo_number: An interger between 1 and 31 indicating the combinations of S, E, A, D, and T modules to be included 
  #			in the simulation. The full list of these combinations can be printed using the function combo_of_choice(28, TRUE).
  # 		We are currently using combinations 25,28,29,and 31 as our four competing models for the spread of agriculture.  
  #
  #    myWorld: Matrix that defines the scope of the available world and acts as a data hub for organizing and reporting 	  
  #			results from the different elements of the simulation. 
  #
  #    number_of_time_steps: An integer indicating how many iterations the simulation will calculated before writing the data 
  #			file. 
  #
  #    nbs: A list of the available neighbors for each spatial point. This is passed to the function for calculating the interaction 
  #			of neighbors through time. 
  #
  #    number_of_tips: An interger indicating the number of tree tips the simulation should be truncated to. The default is to 
  #			include all the available tips (e.g. 1254 for human languages). 
  #
  # Returns: 
  #    myOut: A list object containing a 'phylo' tree object called mytree in the first position and the myWorld matrix of 
  #      	spatial and tree data in the second position 
  #		
  
  x1 <- 4 #Number of runs per core
  if (replicate_cycle != 1) {
    replicate_cycle <- ((replicate_cycle - 1) * x1) + 1
  }
  count <- 0
  for (i in replicate_cycle:(replicate_cycle + (x1 - 1))) {
  independent <- 1
  count <- count + 1  
    
    # Probability of Arisal
    prob_choose_a <- rexp(4, rate = 9)
    P.Arisal0  <- parameters(prob_choose_a[1], prob_choose_a[2],
                             prob_choose_a[3], prob_choose_a[4],
                             "Env_NonD", "Env_D",
                             "Evol_to_F", "Evol_to_D")
    # P.Arisal0 is the one you should change the parameters
    P.Arisal <- matrix(NA, ncol = 2, nrow = nrow(myWorld)) # probability per cell
    colnames(P.Arisal) <- c("Evolve_to_F", "Evolve_to_D")
    Env.Dom <- myWorld[, 7] == 2
    P.Arisal[Env.Dom, 1] <- P.Arisal0[1, 2]
    P.Arisal[!Env.Dom, 1] <- P.Arisal0[1, 1]
    P.Arisal[Env.Dom, 2] <- P.Arisal0[2, 2]
    P.Arisal[!Env.Dom, 2] <- P.Arisal0[2, 1]
    
    colnames(P.Arisal) <- c("Prob_of_Foraging", "Porb_of_Domestication")
    #####
    prob_choose <- runif(12, 0.1, 1)
    prob_choose[c(4)] <- runif(1, 0.1, (prob_choose[1] - 0.1))
    prob_choose[c(5)] <- runif(1, 0.5, 1) # High extinction
    prob_choose[c(6)] <- runif(1, 0, (prob_choose[3] - 0.1))
    prob_choose[c(9, 10, 12)] <- runif(3, 0.1, prob_choose[11])
    if (count == 1) {
      prob_choose[7:12] <- 0
    }
    if (count == 2) {
      prob_choose[9:12] <- 0
    }
    if (count == 3) {
      prob_choose[7:8] <- 0
      independent <- 0
    }
    if (count == 4) {
      independent <- 0
    }
    P.speciation <- parameters(prob_choose[1], prob_choose[1],
                               prob_choose[2], prob_choose[3],
                               "Env_NonD", "Env_D", "For", "Dom")

    P.extinction  <- parameters(prob_choose[4], prob_choose[4],
                                prob_choose[5], prob_choose[6],
                                "Env_NonD", "Env_D", "For", "Dom")
    
    
    P.diffusion <- parameters(0, prob_choose[7],
                              prob_choose[8], 0,
                              "Target_For", "Target_Dom",
                              "Source_For", "Source_Dom")
    
    P.TakeOver <- parameters(prob_choose[9], prob_choose[10],
                             prob_choose[11], prob_choose[12],
                             "Target_For", "Target_Dom",
                             "Source_For", "Source_Dom")
    multiplier <- 1 # always 1 now.
    
    myOut <- RunSimUltimate(myWorld, P.extinction, P.speciation, 
                            P.diffusion, P.Arisal, P.TakeOver, nbs, independent,
                            N.steps = number_of_time_steps, silent = TRUE, 
                            multiplier = multiplier)
    # Count refers to the combo, 1 = null, 2 = diffusion, 3 = Takeover, 4 = full
    save(myOut,  file= paste0("./Module_1_outputs/myOut_rep_",
                              formatC(replicate_cycle, width = 2,flag = 0),
                              "_combo_",
                              formatC(count, width = 2,flag = 0),
                              "_","params", "_P.speciation_",
                              paste(formatC(P.speciation, width = 2,flag = 0), collapse="_"),"_P.extinction_",
                              paste(formatC(P.extinction, width = 2,flag = 0), collapse="_"), "_P.diffusion_",
                              paste(formatC(P.diffusion, width = 2,flag = 0), collapse="_"), "_P.TO_",
                              paste(formatC(P.TakeOver, width = 2,flag = 0), collapse="_"),"_P.Arisal_",
                              paste(formatC(P.Arisal0, width = 2,flag = 0), collapse="_"),
                              "_timesteps_", number_of_time_steps, "_.Rdata"))
    
    Sim_statistics <- Module_2(myOut)
    
    save(Sim_statistics, file= paste0("./Module_2_outputs/Sim_stats_rep_",
                                      formatC(replicate_cycle, width = 2,flag = 0),
                                      "_combo_",
                                      formatC(count, width = 2,flag = 0),
                                      "_","params", "_P.speciation_",
                                      paste(formatC(P.speciation, width = 2,flag = 0), collapse="_"),"_P.extinction_",
                                      paste(formatC(P.extinction, width = 2,flag = 0), collapse="_"), "_P.diffusion_",
                                      paste(formatC(P.diffusion, width = 2,flag = 0), collapse="_"), "_P.TO_",
                                      paste(formatC(P.TakeOver, width = 2,flag = 0), collapse="_"),"_P.Arisal_",
                                      paste(formatC(P.Arisal0, width = 2,flag = 0), collapse="_"),
                                      "_timesteps_", number_of_time_steps, "_.Rdata"))
    replicate_cycle <- replicate_cycle + 1
  }
  
}


```


```{r}
# This is a large data table including all extant languages (~7000 from Glottolog) matched with D-place data. If D-place provided centroid values, we used those. If D-place didn't include centroid values or the location wasn't included in the larger dataset, then the centroid values from Glottolog were used instead. 
language_centroids
```

```{r}
# These are environmental suitability values for each location. Suitability defines how good the area is for farming. This is the number of potential domesticated/domesticatable species. 
head(suitability2)
conds <- suitability2
conds <- ifelse(conds <= 21, 1, 2) # here we reformat the count of potential domesticatable species into a binary category of suitable for farming vs. not suitable for farming (designated as 1 and 2 respectively. )
conds[is.na(conds)] <- sample(c(1, 2), sum(is.na(conds)), replace = TRUE) 
head(conds)
```



```{r}
# There is an object 'coords' in FARM that we are replacing here with a different set of coords. The one included in FARM has ~1200 coords and the new one has ~7000 coords
#V1 = longitude, V2=latitude in the FARM included coords

#####################################################################
coords <- as.matrix(apply(language_centroids[, 3:4], 2, as.numeric)) #coords
head(coords) 

```


```{r}
#plot those points in coords object
library(maps)
map()
points(coords, pch=19, col=adjustcolor("cornflowerblue", alpha=0.8), cex=.5)
```



```{r}
##### Specify simulation parameters #################################

number_of_tips <- length(coords[,1])
number_of_time_steps_a <- 30000
#replicate_cycle <- c(1)  #number of replicates
#####################################################################
data("parameters.table")
```


```{r}
BuildWorld <- function (coords, conditions) 
{
    n <- nrow(coords)
    myWorld <- matrix(ncol = 8, nrow = n)
    myWorld[, 2] <- coords[, 1]
    myWorld[, 3] <- coords[, 2]
    myWorld[, 8] <- 1:n
    myWorld[, 1] <- 1:n
    myWorld[, 7] <- conditions
    colnames(myWorld) <- c("cellID", "Longitude", "Latitude", 
        "Parent", "BirthT", "Trait", "Environment", "TipLabel")
    return(myWorld)
}
```


```{r}
sub <- sample(1:nrow(coords), nrow(coords)) # subsample (remove when running for all)
system.time(
  myWorld <- BuildWorld(coords[sub, ], conds[sub, ])
)

head(myWorld)
```


```{r}
?knearneigh
```



```{r}
nbs <- knn2nb(knearneigh(coords[sub, ], k = 7, longlat = TRUE),
              sym = TRUE) # 7 symmetric neighbors
n.obs <- sapply(nbs, length)
seq.max <- seq_len(max(n.obs))
nbs <- t(sapply(nbs, "[", i = seq.max))
nbs
```


```{r}
#NAI <- 1000
args <- commandArgs(trailingOnly = FALSE)
NAI <- as.numeric(args[7])
# setwd("~/Box Sync/colliding ranges/Simulations_humans/big world cluster outputs")

```



```{r}


sim_run_cluster(replicate_cycle = NAI,
                myWorld, number_of_time_steps = number_of_time_steps_a, 
                nbs, number_of_tips = nrow(myWorld))

```






















