// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DropTip
NumericVector DropTip(NumericMatrix x, NumericVector extinct);
RcppExport SEXP FARM_DropTip(SEXP xSEXP, SEXP extinctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type extinct(extinctSEXP);
    rcpp_result_gen = Rcpp::wrap(DropTip(x, extinct));
    return rcpp_result_gen;
END_RCPP
}
// NewTip
NumericMatrix NewTip(NumericMatrix x, int parent, int child, double branch);
RcppExport SEXP FARM_NewTip(SEXP xSEXP, SEXP parentSEXP, SEXP childSEXP, SEXP branchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type parent(parentSEXP);
    Rcpp::traits::input_parameter< int >::type child(childSEXP);
    Rcpp::traits::input_parameter< double >::type branch(branchSEXP);
    rcpp_result_gen = Rcpp::wrap(NewTip(x, parent, child, branch));
    return rcpp_result_gen;
END_RCPP
}
